
//! Module lexer is generated by GoGLL. Do not edit.

use crate::token;

use std::{fs, io};
use std::rc::Rc;

type State = usize;

const NULL_STATE: State = usize::MAX ;

/**
Lexer contains both the input Vec<char> and the Vec<token::Token>
parsed from the input
*/
pub struct Lexer {
	/// i is the input vector of char
	i: Rc<Vec<char>>,

	/// tokens is the vector of tokens constructed by the lexer from I
	pub tokens: Vec<Rc<token::Token>>
}

impl Lexer {
	/**
	new_file constructs a Lexer created from the input file, fname. 

	If the input file is a markdown file new_file process treats all text outside
	code blocks as whitespace. All text inside code blocks are treated as input text.

	If the input file is a normal text file new_file treats all text in the inputfile
	as input text.
	*/
	#[allow(dead_code)]
	pub fn new_file(fname: &String) -> io::Result<Rc<Lexer>> {
		let i = Rc::new(load_file(fname)?);
		Ok(Lexer::new(i))
	}

	/**
	new constructs a Lexer from a Vec<char>. 
	
	All contents of the input are treated as input text.
	*/
	pub fn new(input: Rc<Vec<char>>) -> Rc<Lexer> {
		let mut lex = Lexer{
			i:      input.clone(),
			tokens: Vec::new(),
		};
		let mut lext = 0;
		while lext < lex.i.len() {
			while lext < lex.i.len() && lex.i[lext].is_whitespace() {
				lext += 1
			}
			if lext < lex.i.len() {
				let tok = lex.scan(lext);
				lext = tok.rext;
				if !tok.suppress() {
					lex.add_token(tok)
				}
			}
		}
		lex.add(token::Type::EOF, input.len(), input.len());
		Rc::new(lex)
	}

	fn add(&mut self, t: token::Type, lext: usize, rext: usize) {
		self.add_token(token::new(t, lext, rext, &self.i))
	}
	
	fn add_token(&mut self, tok: Rc<token::Token>) {
		self.tokens.push(tok)
	}
	
	fn scan(&mut self, i: usize) -> Rc<token::Token> {
		let mut s: State = 0;
		let mut typ = token::Type::Error;
		let mut rext = i;

		while s != NULL_STATE {
			if rext >= self.i.len() {
				typ = ACCEPT[s];
				s = NULL_STATE
			} else {
				typ = ACCEPT[s];
				s = NEXT_STATE[s](self.i[rext]);
				if s != NULL_STATE || typ == token::Type::Error {
					rext += 1
				}
			}
		}
		return token::new(typ, i, rext, &self.i)
	}

	/// get_line_column returns the (line, column) of char[i] in the input
	#[allow(dead_code)]
	pub fn get_line_column(&self, i: usize) -> (usize, usize) {
		let mut line = 1;
		let mut col = 1;
		let mut j = 0;
		while j < i {
			match self.i[j] {
			'\n' => {
				line += 1;
				col = 1
			},
			'\t' => col += 4,
			_ => col += 1
			}
			j += 1
		}
		(line, col)
	}
	
	/// get_line_column_of_token returns the (line, column) of token[i] 
	/// in the input
	#[allow(dead_code)]
	pub fn get_line_column_of_token(&self, i: usize) -> (usize, usize) {
		self.get_line_column(self.tokens[i].lext)
	}

	// get_string returns the input string from the left extent of Token[lext] to
	// the right extent of Token[rext]
	#[allow(dead_code)]
	pub fn get_string(&self, lext: usize, rext: usize) -> String {
		let lext = self.tokens[lext].lext;
		let rext = self.tokens[rext].rext;
		self.i[lext..rext].iter().collect::<String>()
	}
	
	}
/*** End of Lexer implementation ***/


fn load_file(fname: &String) -> io::Result<Vec<char>> {
	let input = fs::read_to_string(fname)?;
	let mut input: Vec<char> = input.chars().collect();
	if fname.ends_with(".md") {
        load_md(&mut input)?;
        Ok(input)
	} else {
		Ok(input)
	}
}

fn load_md(input: &mut Vec<char>) -> io::Result<()> {
    let mut i = 0;
    let mut text = true;
    while i < input.len() {
        if i <= input.len() - 3 && 
        || -> bool { input[i] == '`' && input[i+1] == '`' && input[i+2] == '`' }()
        {
            text = !text;
            for j in i..i+3 {
                input[j] = ' ';
            }
            i += 3;
        }
        if i < input.len() {
            if text {
                match input[i] {
                    '\n' => input[i] = '\n',
                    _ => input[i] = ' ',
                }
            }
            i += 1;
        }
    }
    Ok(())
}

#[allow(dead_code)]
fn any(r: char, set: &'static [char]) -> bool {
	for r1 in set.iter() {
		if &r == r1 {
			return true
		}
	}
	return false
}

#[allow(dead_code)]
fn not(r: char, set: &'static [char]) -> bool {
	for r1 in set.iter() {
		if &r == r1 {
			return false
		}
	}
	return true
}

static ACCEPT: [token::Type; 81] = [ 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_4, 
    token::Type::T_19, 
    token::Type::T_22, 
    token::Type::Error, 
    token::Type::T_3, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_16, 
    token::Type::T_2, 
    token::Type::T_23, 
    token::Type::T_0, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_17, 
    token::Type::T_20, 
    token::Type::T_26, 
    token::Type::T_12, 
    token::Type::Error, 
    token::Type::T_24, 
    token::Type::Error, 
    token::Type::T_15, 
    token::Type::T_16, 
    token::Type::T_7, 
    token::Type::T_9, 
    token::Type::Error, 
    token::Type::T_4, 
    token::Type::T_9, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_16, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_13, 
    token::Type::T_14, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_9, 
    token::Type::T_16, 
    token::Type::T_16, 
    token::Type::T_16, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_10, 
    token::Type::Error, 
    token::Type::T_18, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_4, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_8, 
    token::Type::T_11, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_1, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::Error, 
    token::Type::T_25, 
    token::Type::T_5, 
    token::Type::Error, 
    token::Type::T_21, 
    token::Type::Error, 
    token::Type::T_6, 
];

pub type NextFun = dyn Fn(char) -> State + Sync;

static NEXT_STATE: &'static [&NextFun; 81] = &[  
	// Set0 
	&|c| -> State {  
        if c == '"' { return 1 }; 
        if c == '#' { return 2 }; 
        if c == '(' { return 3 }; 
        if c == ')' { return 4 }; 
        if c == '+' { return 5 }; 
        if c == ',' { return 6 }; 
        if c == '-' { return 7 }; 
        if c == '.' { return 8 }; 
        if c == '/' { return 9 }; 
        if c == '0' { return 10 }; 
        if c == ':' { return 11 }; 
        if c == ';' { return 12 }; 
        if c == '=' { return 13 }; 
        if c == 'b' { return 14 }; 
        if c == 'c' { return 15 }; 
        if c == 'e' { return 16 }; 
        if c == 'f' { return 17 }; 
        if c == 'i' { return 18 }; 
        if c == 'l' { return 19 }; 
        if c == 'r' { return 20 }; 
        if c == 'w' { return 21 }; 
        if c == '{' { return 22 }; 
        if c == '}' { return 23 }; 
        if any(c, &['\t','\n','\r',' ']) { return 24 }; 
        if c.is_uppercase() { return 25 }; 
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 10 }; 
        if any(c, &['+','-']) { return 26 }; 
        NULL_STATE
	}, 
	// Set1 
	&|c| -> State {  
        if c == '"' { return 27 }; 
        if c == '\\' { return 28 }; 
        if not(c, &['"','\\']) { return 1 }; 
        NULL_STATE
	}, 
	// Set2 
	&|c| -> State {  
        if not(c, &['\n']) { return 2 }; 
        NULL_STATE
	}, 
	// Set3 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set4 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set5 
	&|c| -> State {  
        if c == '+' { return 29 }; 
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 30 }; 
        NULL_STATE
	}, 
	// Set6 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set7 
	&|c| -> State {  
        if c == '-' { return 31 }; 
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 30 }; 
        NULL_STATE
	}, 
	// Set8 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 32 }; 
        NULL_STATE
	}, 
	// Set9 
	&|c| -> State {  
        if c == '*' { return 33 }; 
        if c == '/' { return 34 }; 
        NULL_STATE
	}, 
	// Set10 
	&|c| -> State {  
        if c == '.' { return 35 }; 
        if c == 'b' { return 36 }; 
        if c == 'o' { return 37 }; 
        if c == 'x' { return 38 }; 
        if any(c, &['0','1','2','3','4','5','6','7','8','9','_']) { return 39 }; 
        NULL_STATE
	}, 
	// Set11 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set12 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set13 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set14 
	&|c| -> State {  
        if c == 'r' { return 40 }; 
        NULL_STATE
	}, 
	// Set15 
	&|c| -> State {  
        if c == 'o' { return 41 }; 
        NULL_STATE
	}, 
	// Set16 
	&|c| -> State {  
        if c == 'l' { return 42 }; 
        NULL_STATE
	}, 
	// Set17 
	&|c| -> State {  
        if c == 'o' { return 43 }; 
        if c == 'u' { return 44 }; 
        NULL_STATE
	}, 
	// Set18 
	&|c| -> State {  
        if c == 'f' { return 45 }; 
        if c == 'n' { return 46 }; 
        NULL_STATE
	}, 
	// Set19 
	&|c| -> State {  
        if c == 'e' { return 47 }; 
        NULL_STATE
	}, 
	// Set20 
	&|c| -> State {  
        if c == 'e' { return 48 }; 
        NULL_STATE
	}, 
	// Set21 
	&|c| -> State {  
        if c == 'h' { return 49 }; 
        NULL_STATE
	}, 
	// Set22 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set23 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set24 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set25 
	&|c| -> State {  
        if c == '_' { return 25 }; 
        if c.is_alphabetic() { return 25 }; 
        if c.is_numeric() { return 25 }; 
        NULL_STATE
	}, 
	// Set26 
	&|c| -> State {  
        if c == '+' { return 29 }; 
        if c == '-' { return 31 }; 
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 30 }; 
        NULL_STATE
	}, 
	// Set27 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set28 
	&|c| -> State {  
        if true { return 1 }; 
        NULL_STATE
	}, 
	// Set29 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set30 
	&|c| -> State {  
        if c == '.' { return 35 }; 
        if any(c, &['0','1','2','3','4','5','6','7','8','9','_']) { return 39 }; 
        NULL_STATE
	}, 
	// Set31 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set32 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 32 }; 
        NULL_STATE
	}, 
	// Set33 
	&|c| -> State {  
        if c == '*' { return 50 }; 
        if not(c, &['*']) { return 33 }; 
        NULL_STATE
	}, 
	// Set34 
	&|c| -> State {  
        if not(c, &['\n']) { return 34 }; 
        NULL_STATE
	}, 
	// Set35 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','8','9']) { return 51 }; 
        NULL_STATE
	}, 
	// Set36 
	&|c| -> State {  
        if any(c, &['0','1']) { return 52 }; 
        NULL_STATE
	}, 
	// Set37 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7']) { return 53 }; 
        NULL_STATE
	}, 
	// Set38 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','a','b','c','d','e','f']) { return 54 }; 
        NULL_STATE
	}, 
	// Set39 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','8','9','_']) { return 39 }; 
        NULL_STATE
	}, 
	// Set40 
	&|c| -> State {  
        if c == 'e' { return 55 }; 
        NULL_STATE
	}, 
	// Set41 
	&|c| -> State {  
        if c == 'n' { return 56 }; 
        NULL_STATE
	}, 
	// Set42 
	&|c| -> State {  
        if c == 's' { return 57 }; 
        NULL_STATE
	}, 
	// Set43 
	&|c| -> State {  
        if c == 'r' { return 58 }; 
        NULL_STATE
	}, 
	// Set44 
	&|c| -> State {  
        if c == 'n' { return 59 }; 
        NULL_STATE
	}, 
	// Set45 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set46 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set47 
	&|c| -> State {  
        if c == 't' { return 60 }; 
        NULL_STATE
	}, 
	// Set48 
	&|c| -> State {  
        if c == 't' { return 61 }; 
        NULL_STATE
	}, 
	// Set49 
	&|c| -> State {  
        if c == 'i' { return 62 }; 
        NULL_STATE
	}, 
	// Set50 
	&|c| -> State {  
        if c == '/' { return 63 }; 
        if not(c, &['/']) { return 33 }; 
        NULL_STATE
	}, 
	// Set51 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set52 
	&|c| -> State {  
        if any(c, &['0','1','_']) { return 52 }; 
        NULL_STATE
	}, 
	// Set53 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','_']) { return 53 }; 
        NULL_STATE
	}, 
	// Set54 
	&|c| -> State {  
        if any(c, &['0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','_','a','b','c','d','e','f']) { return 54 }; 
        NULL_STATE
	}, 
	// Set55 
	&|c| -> State {  
        if c == 'a' { return 64 }; 
        NULL_STATE
	}, 
	// Set56 
	&|c| -> State {  
        if c == 'f' { return 65 }; 
        if c == 't' { return 66 }; 
        NULL_STATE
	}, 
	// Set57 
	&|c| -> State {  
        if c == 'e' { return 67 }; 
        NULL_STATE
	}, 
	// Set58 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set59 
	&|c| -> State {  
        if c == 'c' { return 68 }; 
        NULL_STATE
	}, 
	// Set60 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set61 
	&|c| -> State {  
        if c == 'u' { return 69 }; 
        NULL_STATE
	}, 
	// Set62 
	&|c| -> State {  
        if c == 'l' { return 70 }; 
        NULL_STATE
	}, 
	// Set63 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set64 
	&|c| -> State {  
        if c == 'k' { return 71 }; 
        NULL_STATE
	}, 
	// Set65 
	&|c| -> State {  
        if c == 'i' { return 72 }; 
        NULL_STATE
	}, 
	// Set66 
	&|c| -> State {  
        if c == 'i' { return 73 }; 
        NULL_STATE
	}, 
	// Set67 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set68 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set69 
	&|c| -> State {  
        if c == 'r' { return 74 }; 
        NULL_STATE
	}, 
	// Set70 
	&|c| -> State {  
        if c == 'e' { return 75 }; 
        NULL_STATE
	}, 
	// Set71 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set72 
	&|c| -> State {  
        if c == 'g' { return 76 }; 
        NULL_STATE
	}, 
	// Set73 
	&|c| -> State {  
        if c == 'n' { return 77 }; 
        NULL_STATE
	}, 
	// Set74 
	&|c| -> State {  
        if c == 'n' { return 78 }; 
        NULL_STATE
	}, 
	// Set75 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set76 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set77 
	&|c| -> State {  
        if c == 'u' { return 79 }; 
        NULL_STATE
	}, 
	// Set78 
	&|_| -> State {  
        NULL_STATE
	}, 
	// Set79 
	&|c| -> State {  
        if c == 'e' { return 80 }; 
        NULL_STATE
	}, 
	// Set80 
	&|_| -> State {  
        NULL_STATE
	}, 
];
