
// Package symbols is generated by gogll. Do not edit.
package symbols

type Symbol interface{
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol() {}

// NT is the type of non-terminals symbols
type NT int
const( 
	NT_Assignment_Statement NT = iota
	NT_Compound_Statement 
	NT_Declaration_Statement 
	NT_Empty_Statement 
	NT_Expression 
	NT_Expression_Statement 
	NT_For 
	NT_GoGLL 
	NT_IncDec_Expression 
	NT_Literal_Expression 
	NT_Simple_Statement 
	NT_Statement 
	NT_Statement_List 
)

// T is the type of terminals symbols
type T int
const( 
	T_0 T = iota // assign 
	T_1  // break 
	T_2  // colon 
	T_3  // comment 
	T_4  // config 
	T_5  // continue 
	T_6  // dec 
	T_7  // else 
	T_8  // float_literal 
	T_9  // for 
	T_10  // function 
	T_11  // identifier 
	T_12  // if 
	T_13  // in 
	T_14  // inc 
	T_15  // integer_literal 
	T_16  // lbrace 
	T_17  // let 
	T_18  // lparen 
	T_19  // rbrace 
	T_20  // return 
	T_21  // rparen 
	T_22  // semicolon 
	T_23  // string_literal 
	T_24  // while 
	T_25  // whitespace 
)

type Symbols []Symbol

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

var ntToString = []string { 
	"Assignment_Statement", /* NT_Assignment_Statement */
	"Compound_Statement", /* NT_Compound_Statement */
	"Declaration_Statement", /* NT_Declaration_Statement */
	"Empty_Statement", /* NT_Empty_Statement */
	"Expression", /* NT_Expression */
	"Expression_Statement", /* NT_Expression_Statement */
	"For", /* NT_For */
	"GoGLL", /* NT_GoGLL */
	"IncDec_Expression", /* NT_IncDec_Expression */
	"Literal_Expression", /* NT_Literal_Expression */
	"Simple_Statement", /* NT_Simple_Statement */
	"Statement", /* NT_Statement */
	"Statement_List", /* NT_Statement_List */ 
}

var tToString = []string { 
	"assign", /* T_0 */
	"break", /* T_1 */
	"colon", /* T_2 */
	"comment", /* T_3 */
	"config", /* T_4 */
	"continue", /* T_5 */
	"dec", /* T_6 */
	"else", /* T_7 */
	"float_literal", /* T_8 */
	"for", /* T_9 */
	"function", /* T_10 */
	"identifier", /* T_11 */
	"if", /* T_12 */
	"in", /* T_13 */
	"inc", /* T_14 */
	"integer_literal", /* T_15 */
	"lbrace", /* T_16 */
	"let", /* T_17 */
	"lparen", /* T_18 */
	"rbrace", /* T_19 */
	"return", /* T_20 */
	"rparen", /* T_21 */
	"semicolon", /* T_22 */
	"string_literal", /* T_23 */
	"while", /* T_24 */
	"whitespace", /* T_25 */ 
}

var stringNT = map[string]NT{ 
	"Assignment_Statement":NT_Assignment_Statement,
	"Compound_Statement":NT_Compound_Statement,
	"Declaration_Statement":NT_Declaration_Statement,
	"Empty_Statement":NT_Empty_Statement,
	"Expression":NT_Expression,
	"Expression_Statement":NT_Expression_Statement,
	"For":NT_For,
	"GoGLL":NT_GoGLL,
	"IncDec_Expression":NT_IncDec_Expression,
	"Literal_Expression":NT_Literal_Expression,
	"Simple_Statement":NT_Simple_Statement,
	"Statement":NT_Statement,
	"Statement_List":NT_Statement_List,
}
